### ISSUE TITLE
I have installed etckeeper on the server

### ISSUE THREAD

**Issue by cdluminate** [xdlinux/server-config#1]
How do you plan to use this repository?

**Comment by time-river** [comment]
在服务器上，服务器配置文件会放到约定成俗的地方。
那么带来一些问题：
1. 服务器上部署了哪些服务？ 这些服务的配置文件哪些是自定义的？哪些是默认的？
2. 后来者怎么快速了解配置？
3. 假如硬盘损坏，原有的配置文件怎么找回？

这个仓库便是为解决这些问题存在的：
1. 部署过、并且个性化后的服务配置文件会添加到这里。
2. 每个部署的服务具有一个文件夹，文件夹下存在一个`README.md`，简要说明该服务、重要的设置，以及配置文件位置。

从这了解到了`etckeeper`

``` bash
etckeeper/stable,now 1.15 all [installed]
  store /etc in git, mercurial, bzr or darcs
```

讲真，我至今没看到过被同步的`/etc/`。

**Comment by time-river** [comment]
...
忘记了回答标题

```
etckeeper/stable,now 1.15 all [installed]
  store /etc in git, mercurial, bzr or darcs
```

讲真，我至今没看到过被同步的`/etc/`。
而且，那么多配置文件，也不容易搞清楚到底安装了啥服务。

**Comment by cdluminate** [comment]
Closing this issue.
